#ifndef __MEMLAYOUT_H__

#define __MEMLAYOUT_H__

#include <stdint.h>
#include "types.h"

#define KERNEL_OFFSET 0xC0000000
#define KPHADDR(dir) ((void*) (((uint32_t) (dir)) - KERNEL_OFFSET))
#define KVIRTADDR(dir) ((void*) (((uint32_t) (dir)) + KERNEL_OFFSET))

#define KERNEL_VIRT_ADDR 0xC0200000
#define KERNEL_PHYS_ADDR KPHADDR(KERNEL_VIRT_ADDR)

#define KERNEL_STACK (KERNEL_VIRT_ADDR - PAGE_SIZE*254)
#define KERNEL_PAGE_TABLE (KERNEL_VIRT_ADDR - PAGE_SIZE*253)
#define KERNEL_PAGE_DIRECTORY (KERNEL_VIRT_ADDR - PAGE_SIZE*252)

#define LOADER_PHYS_ADDR 0x00100000

#define VIDEO_VIRT_ADDR 0xC00B8000
#define VIDEO_PHYS_ADDR KPHADDR(VIDEO_VIRT_ADDR)

#endif
